// Assembles the GitHub Pages demo (issue #199) into demo-dist/, gitignored.
//
//   npm install && node scripts/build-demo.mjs
//   npx http-server demo-dist        # or any static server, to preview
//
// The demo is public/'s own map modules with exactly one substitution:
// demo/signalk.js lands as signalk.js, so hf.js and friends resolve their
// './signalk.js' import to the snapshot-backed version and run unchanged
// against demo/snapshot.json instead of a Signal K server.
import fssync from 'node:fs'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const PUBLIC = path.join(REPO, 'public')
const DEMO = path.join(REPO, 'demo')
const OUT = path.join(REPO, 'demo-dist')

// Only the map stack and what it imports -- not index.html, not the config
// panel, not remoteEntry.js. The demo is the map and the HF strip, and every
// file here is served to every visitor.
export const PUBLIC_MODULES = [
  'spaceMap.js',
  'mapRaster.js',
  'projection.js',
  'geo.js',
  'aurora.js',
  'drap-colors.js',
  'drapMap.js',
  'hf.js',
  'coastline.js',
  'icon.svg'
]

// coastline.js and vendor/ are generated by sync-coastline.mjs on prepare;
// missing means this ran before npm install, not that the build is optional.
if (!fssync.existsSync(path.join(PUBLIC, 'coastline.js'))) {
  console.error('public/coastline.js missing -- run `npm install` first')
  process.exit(1)
}

await fs.rm(OUT, { recursive: true, force: true })
await fs.mkdir(OUT, { recursive: true })
for (const name of PUBLIC_MODULES) {
  await fs.copyFile(path.join(PUBLIC, name), path.join(OUT, name))
}
await fs.cp(path.join(PUBLIC, 'vendor'), path.join(OUT, 'vendor'), {
  recursive: true
})
await fs.copyFile(path.join(DEMO, 'index.html'), path.join(OUT, 'index.html'))
await fs.copyFile(path.join(DEMO, 'signalk.js'), path.join(OUT, 'signalk.js'))
await fs.copyFile(
  path.join(DEMO, 'snapshot.json'),
  path.join(OUT, 'snapshot.json')
)

console.log(`assembled ${path.relative(REPO, OUT)}/`)
